base_url: "https://doc-online-test.gstyun.cn/webClinic"
login_path: "/login"
#浏览器有头（false）和无头模（true）式切换
headless: true

selectors:
  username: "input[placeholder*='手机号']"
  password: "input[placeholder*='验证码']"
  login_btn: "button:has-text('登录')"
  doctor_radio: "radio"
  confirm_btn: "button:has-text('确认'), button:has-text('确认切换')"
  online_consultation_menu: ".menu-item:has-text('问诊')"

timeout:
  default: 15000
  navigation: 15000

reports:
  html_dir: "reports/html"
  allure_dir: "reports/allure"
  screenshots_dir: "screenshots"
  auth_state: "reports/.auth/state.json"

cleanup:
  days: 3